"""empty message

Revision ID: 504f991047c1
Revises: 997cee7f7199
Create Date: 2025-06-27 11:49:22.554828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504f991047c1'
down_revision = '997cee7f7199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagens')

    # ### end Alembic commands ###
