"""empty message

Revision ID: 5b9ccf94586f
Revises: 504f991047c1
Create Date: 2025-06-27 15:30:36.002653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9ccf94586f'
down_revision = '504f991047c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.Integer(), nullable=True))
        batch_op.drop_column('imagens')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagens', sa.INTEGER(), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
