"""empty message

Revision ID: 997cee7f7199
Revises: a8f7e5ebe93b
Create Date: 2025-06-18 17:01:56.716187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997cee7f7199'
down_revision = 'a8f7e5ebe93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###
