"""empty message

Revision ID: a8f7e5ebe93b
Revises: b396bb619ca5
Create Date: 2025-06-18 16:58:19.333264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f7e5ebe93b'
down_revision = 'b396bb619ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
